### ISSUE TITLE
Running on cloudlab

### ISSUE THREAD

**Issue by dgiantsidi** [ut-osa/boki-benchmarks#1]
Hi,

Would be possible/easy to run boki-benchmarks on cloudlab? e.g., what are the dependencies?

Best,
Dimitra

**Comment by zhipeng-jia** [comment]
Hi Dimitra,

I have no experience with cloudlab. Thus I cannot precisely predict if it's easy or hard to run Boki benchmarks there.

All of the experiment scripts in this repo is designed around AWS EC2 instances. I think somehow it will need non-trivial amount of work to run on other infrastructure.

**Comment by dgiantsidi** [comment]
Hello, 

Thank you for the prompt response :) 

Best,
Dimitra
